databases:
  - name: portfolio_db
    databaseName: portfolio
    user: portfolio_user
    plan: free # or starter, standard, etc.

services:
  - type: web
    name: portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio_db
          property: connectionString
